"""empty message

Revision ID: 683df90ff950
Revises: 
Create Date: 2022-10-28 21:31:59.757948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683df90ff950'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videoModel', sa.Column('trending', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videoModel', 'trending')
    # ### end Alembic commands ###
