"""empty message

Revision ID: fe6a4c97a75c
Revises: 683df90ff950
Create Date: 2022-10-28 22:23:50.013019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6a4c97a75c'
down_revision = '683df90ff950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videoModel', sa.Column('trending', sa.Boolean(), server_default=sa.text('True'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videoModel', 'trending')
    # ### end Alembic commands ###
